services:
  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    command: -a 1.52 express-hello-world
  express-hello-world:
    image: capscience/express-hello-world
    container_name: express-hello-world
    ports:
      - 8080:8080
